<a href="https://colab.research.google.com/github/chandradharvasireddy-19/25BDS0329/blob/main/exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# creating csv file
import csv
headers = ["Employee ID", "Name", "Department", "Age", "Experience", "Salary"]
data = [
    [101, "Vassu Dev", "HR", 28, 4, 55000],
    [102, "Abdul Moiz", "Engineering", 34, 9, 85000],
    [103, "Chandu Vasireddy", "Marketing", 22, 1, 150000],
    [104, "Animesh Panda", "Engineering", 29, 5, 72000],
    [105, "Pranav Mithran", "Finance", 41, 15, 110000],
    [106, "Vaibhav", "HR", 31, 6, 62000],
    [107, "Anay Saxena", "Sales", 25, 2, 48000],
    [108, "Toyesh Lath", "Finance", 36, 10, 95000],
]
with open("employee_salary.csv", mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(data)

In [5]:
#tasks
import pandas as pd #1
df=pd.read_csv("employee_salary.csv") #2
print("first 5 recors")
df.head(5)

first 5 recors

   Employee ID             Name   Department  Age  Experience  Salary
0          101        Vassu Dev           HR   28           4   55000
1          102       Abdul Moiz  Engineering   34           9   85000
2          103  Chandu Vasiredy    Marketing   22           1  150000
3          104    Animesh Panda  Engineering   29           5   72000
4          105   Pranav Mithran      Finance   41          15  110000

In [4]:
print("last five records")
df.tail(5) #4

   Employee ID            Name   Department  Age  Experience  Salary
3          104   Animesh Panda  Engineering   29           5   72000
4          105  Pranav Mithran      Finance   41          15  110000
5          106         Vaibhav           HR   31           6   62000
6          107     Anay Saxena        Sales   25           2   48000
7          108     Toyesh Lath      Finance   36          10   95000

In [6]:
#5
print("Number of rows:",len(df))
print("number of columns:",len(df.columns))

Number of rows: 8
number of columns: 6

In [8]:
#question 2
print("Display column names:")
print(list(df.columns))

Display column names:
['Employee ID', 'Name', 'Department', 'Age', 'Experience', 'Salary']

In [9]:
print("Data Types of Each Column:")
print(df.dtypes)

Data Types of Each Column:
Employee ID     int64
Name           object
Department     object
Age             int64
Experience      int64
Salary          int64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee ID  8 non-null      int64
 1   Name         8 non-null      object
 2   Department   8 non-null      object
 3   Age          8 non-null      int64
 4   Experience   8 non-null      int64
 5   Salary       8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

In [11]:
print(df.describe())

       Employee ID        Age  Experience         Salary
count      8.00000   8.000000      8.0000       8.000000
mean     104.50000  30.750000      6.5000   84625.000000
std        2.44949   6.135378      4.6291   33627.953933
min      101.00000  22.000000      1.0000   48000.000000
25%      102.75000  27.250000      3.5000   60250.000000
50%      104.50000  30.000000      5.5000   78500.000000
75%      106.25000  34.500000      9.2500   98750.000000
max      108.00000  41.000000     15.0000  150000.000000

In [13]:
missing_counts = df.isnull().sum()
print(missing_counts)

Employee ID    0
Name           0
Department     0
Age            0
Experience     0
Salary         0
dtype: int64

In [14]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

Employee ID    0.0
Name           0.0
Department     0.0
Age            0.0
Experience     0.0
Salary         0.0
dtype: float64

In [15]:
print(missing_counts.sort_values(ascending=False))

Employee ID    0
Name           0
Department     0
Age            0
Experience     0
Salary         0
dtype: int64