<a href="https://colab.research.google.com/github/chandradharvasireddy-19/25BDS0329/blob/main/exp5_04.08.2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
weight=[36,38,45,67,76,49,56,89,109,81]
bins=[30,45,60,80,110]
cat=pd.cut(weight,bins)
cat

[(30, 45], (30, 45], (30, 45], (60, 80], (60, 80], (45, 60], (45, 60], (80, 110], (80, 110], (80, 110]]
Categories (4, interval[int64, right]): [(30, 45] < (45, 60] < (60, 80] < (80, 110]]

In [2]:
#checking how many values in each bin
pd.value_counts(cat)

/tmp/ipykernel_1900/888665261.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cat)

(30, 45]     3
(80, 110]    3
(45, 60]     2
(60, 80]     2
Name: count, dtype: int64

In [3]:
bin_names=['Weak','Moderate','Fit','Obesity']
pd.cut(weight, bins, labels=bin_names)

['Weak', 'Weak', 'Weak', 'Fit', 'Fit', 'Moderate', 'Moderate', 'Obesity', 'Obesity', 'Obesity']
Categories (4, object): ['Weak' < 'Moderate' < 'Fit' < 'Obesity']

In [4]:
import numpy as np
pd.cut(np.random.rand(30), 6, precision=2)

[(0.19, 0.35], (0.033, 0.19], (0.52, 0.68], (0.033, 0.19], (0.19, 0.35], ..., (0.35, 0.52], (0.68, 0.84], (0.84, 1.0], (0.84, 1.0], (0.84, 1.0]]
Length: 30
Categories (6, interval[float64, right]): [(0.033, 0.19] < (0.19, 0.35] < (0.35, 0.52] <
                                           (0.52, 0.68] < (0.68, 0.84] < (0.84, 1.0]]

In [6]:
randomNumbers = np.random.rand(1000)
category3 = pd.qcut(randomNumbers, 3)
category3

[(-0.0009604, 0.311], (-0.0009604, 0.311], (-0.0009604, 0.311], (0.661, 1.0], (0.661, 1.0], ..., (0.661, 1.0], (-0.0009604, 0.311], (0.311, 0.661], (0.311, 0.661], (-0.0009604, 0.311]]
Length: 1000
Categories (3, interval[float64, right]): [(-0.0009604, 0.311] < (0.311, 0.661] < (0.661, 1.0]]

In [7]:
pd.value_counts(category3)

/tmp/ipykernel_1900/647498483.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category3)

(0.661, 1.0]           334
(-0.0009604, 0.311]    333
(0.311, 0.661]         333
Name: count, dtype: int64

In [8]:
df=pd.read_csv('/content/Males.csv')
df.head(10)

,rownames,nr,year,school,exper,union,ethn,maried,health,wage,industry,occupation,residence
0,1,13,1980,14,1,no,other,no,no,1.197540,Business_and_Repair_Service,Service_Workers,north_east
1,2,13,1981,14,2,yes,other,no,no,1.853060,Personal_Service,Service_Workers,north_east
2,3,13,1982,14,3,no,other,no,no,1.344462,Business_and_Repair_Service,Service_Workers,north_east
3,4,13,1983,14,4,no,other,no,no,1.433213,Business_and_Repair_Service,Service_Workers,north_east
4,5,13,1984,14,5,no,other,no,no,1.568125,Personal_Service,"Craftsmen, Foremen_and_kindred",north_east
5,6,13,1985,14,6,no,other,no,no,1.699891,Business_and_Repair_Service,"Managers, Officials_and_Proprietors",north_east
6,7,13,1986,14,7,no,other,no,no,-0.720263,Business_and_Repair_Service,"Managers, Officials_and_Proprietors",north_east
7,8,13,1987,14,8,no,other,no,no,1.669188,Business_and_Repair_Service,"Managers, Officials_and_Proprietors",north_east
8,9,17,1980,13,4,no,other,no,no,1.675962,Trade,"Managers, Officials_and_Proprietors",north_east
9,10,17,1981,13,5,no,other,no,no,1.518398,Trade,"Managers, Officials_and_Proprietors",north_east

In [10]:
df['new']=df['nr']*df['school']
df

,rownames,nr,year,school,exper,union,ethn,maried,health,wage,industry,occupation,residence,new
0,1,13,1980,14,1,no,other,no,no,1.197540,Business_and_Repair_Service,Service_Workers,north_east,182
1,2,13,1981,14,2,yes,other,no,no,1.853060,Personal_Service,Service_Workers,north_east,182
2,3,13,1982,14,3,no,other,no,no,1.344462,Business_and_Repair_Service,Service_Workers,north_east,182
3,4,13,1983,14,4,no,other,no,no,1.433213,Business_and_Repair_Service,Service_Workers,north_east,182
4,5,13,1984,14,5,no,other,no,no,1.568125,Personal_Service,"Craftsmen, Foremen_and_kindred",north_east,182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4355,4356,12548,1983,9,8,no,other,yes,no,1.591879,Construction,"Craftsmen, Foremen_and_kindred",NaN,112932
4356,4357,12548,1984,9,9,yes,other,yes,no,1.212543,Construction,"Craftsmen, Foremen_and_kindred",NaN,112932
4357,4358,12548,1985,9,10,no,other,yes,no,1.765962,Construction,"Craftsmen, Foremen_and_kindred",NaN,112932
4358,4359,12548,1986,9,11,yes,other,yes,no,1.745894,Professional_and_Related Service,"Craftsmen, Foremen_and_kindred",NaN,112932
4359,4360,12548,1987,9,12,yes,other,yes,no,1.466543,Public_Administration,"Craftsmen, Foremen_and_kindred",NaN,112932

In [11]:
n=df['new']
n[np.abs(n) > 3000]

112       3270
113       3270
114       3270
115       3270
116       3270
         ...
4355    112932
4356    112932
4357    112932
4358    112932
4359    112932
Name: new, Length: 4232, dtype: int64

In [13]:
df[np.abs(n) > 34634]

,rownames,nr,year,school,exper,union,ethn,maried,health,wage,industry,occupation,residence,new
1200,1201,2685,1980,13,2,no,other,no,no,1.840042,Professional_and_Related Service,"Professional, Technical_and_kindred",NaN,34905
1201,1202,2685,1981,13,3,no,other,no,no,1.798149,Professional_and_Related Service,"Professional, Technical_and_kindred",south,34905
1202,1203,2685,1982,13,4,no,other,no,no,2.098899,Professional_and_Related Service,"Professional, Technical_and_kindred",south,34905
1203,1204,2685,1983,13,5,no,other,no,no,2.267007,Professional_and_Related Service,"Professional, Technical_and_kindred",south,34905
1204,1205,2685,1984,13,6,no,other,no,no,2.369424,Professional_and_Related Service,"Professional, Technical_and_kindred",south,34905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4355,4356,12548,1983,9,8,no,other,yes,no,1.591879,Construction,"Craftsmen, Foremen_and_kindred",NaN,112932
4356,4357,12548,1984,9,9,yes,other,yes,no,1.212543,Construction,"Craftsmen, Foremen_and_kindred",NaN,112932
4357,4358,12548,1985,9,10,no,other,yes,no,1.765962,Construction,"Craftsmen, Foremen_and_kindred",NaN,112932
4358,4359,12548,1986,9,11,yes,other,yes,no,1.745894,Professional_and_Related Service,"Craftsmen, Foremen_and_kindred",NaN,112932
4359,4360,12548,1987,9,12,yes,other,yes,no,1.466543,Public_Administration,"Craftsmen, Foremen_and_kindred",NaN,112932

In [14]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [16]:
data = {
 'Age': [24, 57, 45, 35, 62],
 'Salary': [50000, 64000, 120000, 85000, 1200000]
}
df = pd.DataFrame(data)
df

   Age   Salary
0   24    50000
1   57    64000
2   45   120000
3   35    85000
4   62  1200000

In [17]:
min_max_scaler = MinMaxScaler()
df_min_max = pd.DataFrame(
 min_max_scaler.fit_transform(df),
 columns=df.columns
)
df_min_max

        Age    Salary
0  0.000000  0.000000
1  0.868421  0.012174
2  0.552632  0.060870
3  0.289474  0.030435
4  1.000000  1.000000

In [18]:
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(
 standard_scaler.fit_transform(df),
 columns=df.columns
)
df_standard

        Age    Salary
0 -1.476560 -0.565609
1  0.888803 -0.534409
2  0.028671 -0.409609
3 -0.688106 -0.487609
4  1.247192  1.997236

In [19]:
# 4. Robust Scaling (Immune to Outliers)
robust_scaler = RobustScaler()
df_robust = pd.DataFrame(
    robust_scaler.fit_transform(df),
    columns=df.columns
)
df_robust

        Age     Salary
0 -0.954545  -0.625000
1  0.545455  -0.375000
2  0.000000   0.625000
3 -0.454545   0.000000
4  0.772727  19.910714